"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$line_break\
$character"""

[directory]
read_only = " 󰌾"

[git_branch]
format = '[on ](dimmed)[$branch(:$remote_branch) ]($style)'
style = "green"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "yellow dimmed"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
staged = "+${count}"
modified = "!${count}"
untracked = "?${count}"
conflicted = "=${count}"
deleted = "x${count}"
renamed = "»${count}"
stashed = "*${count}"

[fill]
symbol = " "

[cmd_duration]
min_time = 2_000
format = "[$duration]($style)"
style = "bold yellow"
